package it.overnet.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import it.overnet.utilities.DBUtilityConnection;

public class CrudUser {
	public static boolean createTable() throws Exception {

		Connection dbConnection = null;
		Statement statement = null;
		ResultSet resulSet = null;

		boolean check = false;
		String createTableSQL = "CREATE  TABLE REGISTRATION "
				+ "(ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL , " + " USERNAME VARCHAR(255) UNIQUE, "
				+ " PASSWORD VARCHAR(255), " + " CONSTRAINT REGISTRATION_PK PRIMARY KEY ( id ))";

		try {
			dbConnection = DBUtilityConnection.getDBConnection();
			statement = dbConnection.createStatement();

			System.out.println(createTableSQL);

			statement.execute(createTableSQL);
			
			resulSet = statement.executeQuery(createTableSQL);
			if (resulSet.next()) {
				check = true;
			}
			System.out.println("Tabella \"REGISTRATION\" creata con successo!");

		} catch (SQLException e) {

			System.err.println(e.getMessage());

		} finally {

			if (statement != null) {
				statement.close();
			}

			if (dbConnection != null) {
				dbConnection.close();
			}

		}
		return check;
	}

	public static boolean insertRecordIntoTable(String username, String password) throws Exception {

		Connection dbConnection = null;
		PreparedStatement preparedStatement = null;

		String insertTableSQL = "INSERT INTO REGISTRATION" + "(ID, USERNAME, PASSWORD) VALUES" + "(default,?,?)";
		ResultSet resulSet = null;
		Statement statement = null;
		boolean check = false;
		try {
			dbConnection = DBUtilityConnection.getDBConnection();
			preparedStatement = dbConnection.prepareStatement(insertTableSQL);
			statement = dbConnection.prepareStatement(insertTableSQL);
			preparedStatement.setString(1, username);
			preparedStatement.setString(2, password);

			// execute insert SQL statement
			preparedStatement.executeUpdate();
			
			resulSet = statement.executeQuery(insertTableSQL);
			if (resulSet.next()) {
				check = true;
			}

			System.out.println("Record inserito nella tabella REGISTRATION!");

		} catch (SQLException e) {

			System.err.println(e.getMessage());

		} finally {

			if (preparedStatement != null) {
				preparedStatement.close();
			}

			if (dbConnection != null) {
				dbConnection.close();
			}

		}
		return check;
	}

	public static boolean selectRecordIntoTable(String username, String password) throws Exception {
		Connection dbConnection = null;
		Statement statement = null;
		String selectTableSQL = "SELECT USERNAME, PASSWORD FROM REGISTRATION WHERE USERNAME= '" + username
				+ "' AND PASSWORD ='" + password + "'";
		System.out.println(selectTableSQL);
		ResultSet resulSet = null;

		boolean check = false;

		try {

			dbConnection = DBUtilityConnection.getDBConnection();
			statement = dbConnection.prepareStatement(selectTableSQL);

			resulSet = statement.executeQuery(selectTableSQL);
			if (resulSet.next()) {
				check = true;
			}

		} catch (SQLException e) {

			System.err.println(e.getMessage());

		} finally {

			if (statement != null) {
				statement.close();
			}

			if (dbConnection != null) {
				dbConnection.close();
			}
		}
		return check;

	}
}
